---
title: "Forecasting"
author: "John Russell"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Both influenza and pneumonia are major concerns in the health field. Pneumonia is the world’s leading cause of death for children under 5 years. It is also the leading cause of hospital admissions for adults in the US other than women giving birth (1). With that many hospitalizations, it is important that the treatment is effective and people are able to recover.

When looking at the given dataset, which is the collection of weekly deaths due to Influenza (Flu) and Pneumonia from 2009-2018, there are a number of possible questions that could be asked. Which region has the highest percentage of death due to the flu and pneumonia? Does age play a significant role in dying due to the infections? And, given how high the percentage of deaths due to the two infections in 2018 was, is there a possibility of an upwards trend?